# Generated by Django 3.2.16 on 2023-01-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_image_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
