# Generated by Django 3.2.16 on 2023-01-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20230125_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='description_long',
        ),
        migrations.RemoveField(
            model_name='place',
            name='description_short',
        ),
        migrations.AddField(
            model_name='place',
            name='long_description',
            field=models.TextField(null=True, verbose_name='Описание полное'),
        ),
        migrations.AddField(
            model_name='place',
            name='short_description',
            field=models.TextField(null=True, verbose_name='Описание короткое'),
        ),
    ]
