# Generated by Django 4.1.5 on 2023-01-27 01:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_image_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='long_description',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание полное'),
        ),
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание короткое'),
        ),
    ]
